//קובץ ההגדרות של Gradle

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.hand2font'
version = '0.0.1-SNAPSHOT'
description = 'Hand2Font project'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot Starters
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// Database
	runtimeOnly 'org.postgresql:postgresql'
	// Lombok (Helper for Boilerplate code)
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// JSON Web Token (JWT) - Updated versions
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
	// DevTools for faster development
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	//amqp
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	//WebSockets
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	//ObjectMapper
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	implementation 'com.bucket4j:bucket4j-core:8.1.0'

}

tasks.named('test') {
	useJUnitPlatform()
}
