
spring.application.name=hand2font

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hand2font_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG

# HTTPS
server.port=8443

# SSL
server.ssl.enabled=true

# Keystore
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
#  Spring Boot
spring.main.banner-mode=console
spring.main.web-application-type=servlet

#Secret Key for JWT
jwt.secret=${JWT_SECRET}

#  RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# virtual-host
spring.rabbitmq.virtual-host=/
spring.rabbitmq.ssl.enabled=false

# images
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#
spring.http.multipart.max-file-size=20MB
spring.http.multipart.max-request-size=20MB